apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ecrivera-tier3
  region: ap-southeast-1

vpc:
  id: vpc-03645c914516c2d19
  cidr: "10.44.0.0/16"
  subnets:
    public:
      ap-southeast-1a:
        id: subnet-07cbf45d5d4efc24b
      ap-southeast-1b:
        id: subnet-0bf9330ee5e3a8059
    private:
      ap-southeast-1a:
        id: subnet-0eee43485e13f0e81
      ap-southeast-1b:
        id: subnet-0c9014a7f1b576fa8

nodeGroups:
  - name: ecrivera-tier3-node
    instanceType: t3a.micro
    desiredCapacity: 2
  - name: ecrivera-tier3-workers
    instanceType: t3a.micro
    desiredCapacity: 2
    privateNetworking: true