apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecrivera-tier3
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: erivera-tier3-ecr
          image: 329511059546.dkr.ecr.ap-southeast-1.amazonaws.com/erivera-tier3-ecr:cb53785
          ports:
            - containerPort: 1337